version: "3.8"
services:
  app:
    container_name: appBuild
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT:-8080}:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/respakdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password

  db:
    container_name: dbBuild
    image: postgres:9.6
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: respakdb
    # ports:
    #   - "5432:5432" # PostgreSQL доступен на localhost:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
